# Build matrix / environment variable are explained on:
# https://docs.travis-ci.com/user/customizing-the-build/
# This file can be validated on:
# http://lint.travis-ci.org/

language: cpp

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: BUILD_TYPE=Release CXX=g++-10 CXX_FLAGS="-std=c++17 -Wdeprecated"
    - os: linux
      dist: bionic
      compiler: clang
      env: BUILD_TYPE=Release CXX=clang++-10 CXX_FLAGS="-std=c++17 -Wdeprecated"
    - os: osx
      osx_image: xcode12.2
      compiler: gcc
      env: BUILD_TYPE=Release CC=gcc-10 CXX=g++-10 CXX_FLAGS="-std=c++17 -Wdeprecated" HOMEBREW_LOGS=~/homebrew-logs HOMEBREW_TEMP=~/homebrew-temp


script: ./ci/travis.sh

# This section installs the necessary dependencies.
addons:
  apt:
    packages:
    - g++-10
    - clang-10
    - clang++-10
    update: true
  homebrew:
    packages:
    - gcc@10
    update: true

notifications:
  email: false
